Traceback (most recent call last):
  File "/Users/kyas/opt/anaconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/kyas/opt/anaconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/kyas/opt/anaconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/kyas/opt/anaconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/kyas/opt/anaconda3/envs/reaktoro-jupyter-book/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/kyas/opt/anaconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/kyas/opt/anaconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/kyas/opt/anaconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------

conditions = EquilibriumConditions(specs)
conditions.temperature(30.0, "celsius")
conditions.pressure(5.0, "atm")
conditions.set("pH", 7.0)  # remember the symbol "pH" introduced before? you're using it here!

solver = EquilibriumSolver(specs)
solver.solve(state, conditions)

aprops = AqueousProps(state)
print(aprops)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Input [0;32mIn [10][0m, in [0;36m<cell line: 7>[0;34m()[0m
[1;32m      4[0m conditions[38;5;241m.[39mset([38;5;124m"[39m[38;5;124mpH[39m[38;5;124m"[39m, [38;5;241m7.0[39m)  [38;5;66;03m# remember the symbol "pH" introduced before? you're using it here![39;00m
[1;32m      6[0m solver [38;5;241m=[39m EquilibriumSolver(specs)
[0;32m----> 7[0m [43msolver[49m[38;5;241;43m.[39;49m[43msolve[49m[43m([49m[43mstate[49m[43m,[49m[43m [49m[43mconditions[49m[43m)[49m
[1;32m      9[0m aprops [38;5;241m=[39m AqueousProps(state)
[1;32m     10[0m [38;5;28mprint[39m(aprops)

Input [0;32mIn [8][0m, in [0;36m<lambda>[0;34m(props, w)[0m
[1;32m      5[0m pHConstraint [38;5;241m=[39m ConstraintEquation()
[1;32m      6[0m pHConstraint[38;5;241m.[39mid [38;5;241m=[39m [38;5;124m"[39m[38;5;124mpHConstraint[39m[38;5;124m"[39m  [38;5;66;03m# give some identification name to the constraint (it's up to you how you call this)[39;00m
[0;32m----> 7[0m pHConstraint[38;5;241m.[39mfn [38;5;241m=[39m [38;5;28;01mlambda[39;00m props, w: pH(props) [38;5;241m-[39m [38;5;28;43mfloat[39;49m[43m([49m[43mw[49m[43m)[49m  [38;5;66;03m# the residual function defining pH(current) - pH(desired)[39;00m
[1;32m      9[0m specs[38;5;241m.[39mtemperature()
[1;32m     10[0m specs[38;5;241m.[39mpressure()

[0;31mTypeError[0m: float() argument must be a string or a number, not 'autodiff.autodiff4py.VectorXreal1stConstRef'
TypeError: float() argument must be a string or a number, not 'autodiff.autodiff4py.VectorXreal1stConstRef'

