Traceback (most recent call last):
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 627, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/util.py", line 89, in ensure_async
    result = await obj
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/jupyter_client/channels.py", line 230, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 846, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 651, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 701, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 100 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
import numpy as np
temperatures = np.arange(20.0, 91.0, 5.0)   # in celsius
pressures = np.array([1, 10, 100])          # in bar

[solubility_of_calcite(water(), T, P, "water") for P in pressures for T in temperatures];
[solubility_of_calcite(rainwater(), T, P, "rainwater") for P in pressures for T in temperatures];
-------------------

